- name: Tworzenie VM i sieci NAT
  hosts: local
  become: true

  vars:
    bridge_name: nat-net
    vm_name: http-vm
    vm_memory: 1024
    vm_vcpus: 1
    vm_disk: /var/lib/libvirt/images/http-vm.qcow2
    vm_cdrom: /var/lib/libvirt/boot/ubuntu.iso
    vm_network: "{{ bridge_name }}"

  tasks:
    - name: Wgraj plik sieci NAT
      template:
        src: templates/net-nat.xml.j2
        dest: "/tmp/{{ bridge_name }}.xml"

    - name: Zdefiniuj i uruchom sieć NAT
      shell: |
        virsh net-define /tmp/{{ bridge_name }}.xml
        virsh net-start {{ bridge_name }}
        virsh net-autostart {{ bridge_name }}
      ignore_errors: true

    - name: Upewnij się, że dysk VM istnieje
      command: qemu-img create -f qcow2 {{ vm_disk }} 10G
      args:
        creates: "{{ vm_disk }}"

    - name: Tworzenie VM
      command: >
        virt-install --name {{ vm_name }}
        --memory {{ vm_memory }} --vcpus {{ vm_vcpus }}
        --disk path={{ vm_disk }},format=qcow2
        --cdrom {{ vm_cdrom }}
        --network network={{ bridge_name }},model=virtio
        --graphics none --os-type linux --os-variant ubuntu22.04
        --noautoconsole