- name: Ensure base image is downloaded
  get_url:
    url: "{{ vm_image_url }}"
    dest: "{{ vm_base_image }}"
    mode: '0644'

- name: Create VM disk from base image
  command: >
    qemu-img create -f qcow2 -F qcow2 -b {{ vm_base_image }} {{ vm_disk }}
  args:
    creates: "{{ vm_disk }}"

- name: Render user-data
  template:
    src: user-data
    dest: "/tmp/{{ vm_name }}-user-data"

- name: Render meta-data
  template:
    src: meta-data
    dest: "/tmp/{{ vm_name }}-meta-data"

- name: Create cloud-init ISO
  command: >
    cloud-localds -v {{ vm_ci_iso }}
    /tmp/{{ vm_name }}-user-data
    /tmp/{{ vm_name }}-meta-data
  args:
    creates: "{{ vm_ci_iso }}"

- name: Create and start VM via virt-install
  command: >
    virt-install
    --name={{ vm_name }}
    --memory={{ vm_memory }}
    --vcpus={{ vm_vcpus }}
    --disk path={{ vm_disk }},format=qcow2
    --disk path={{ vm_ci_iso }},device=cdrom
    --network network={{ vm_network }}
    --os-variant={{ vm_os_variant }}
    --graphics none
    --import
    --noautoconsole
  args:
    creates: "/etc/libvirt/qemu/{{ vm_name }}.xml"
