vms:
  - name: test-vm-1
    memory: 2048
    vcpus: 2
    disk: /var/lib/libvirt/images/test-vm-1.qcow2
    base_image: /var/lib/libvirt/images/ubuntu-jammy-base.qcow2
    image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
    ci_iso: /var/lib/libvirt/images/test-vm-1-seed.iso
    network: default
    os_variant: ubuntu22.04
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  
  - name: test-vm-2
    memory: 2048
    vcpus: 2
    disk: /var/lib/libvirt/images/test-vm-2.qcow2
    base_image: /var/lib/libvirt/images/ubuntu-jammy-base.qcow2
    image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
    ci_iso: /var/lib/libvirt/images/test-vm-2-seed.iso
    network: default
    os_variant: ubuntu22.04
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  
  - name: test-vm-3
    memory: 2048
    vcpus: 2
    disk: /var/lib/libvirt/images/test-vm-3.qcow2
    base_image: /var/lib/libvirt/images/ubuntu-jammy-base.qcow2
    image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
    ci_iso: /var/lib/libvirt/images/test-vm-3-seed.iso
    network: default
    os_variant: ubuntu22.04
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
