- name: Sprawdź czy sieć {{ vm_network }} już istnieje
  command: virsh net-info {{ vm_network }}
  register: net_check
  ignore_errors: true
  changed_when: false

- name: Pomiń tworzenie sieci jeśli już istnieje
  debug:
    msg: "Sieć {{ vm_network }} już istnieje – pomijam tworzenie."
  when: net_check.rc == 0

- name: Wybierz szablon XML w zależności od typu sieci
  set_fact:
    network_template: "network-{{ network_mode }}.xml.j2"
  when: net_check.rc != 0

- name: Wygeneruj XML sieci
  template:
    src: "{{ network_template }}"
    dest: "/tmp/{{ vm_network }}.xml"
  when: net_check.rc != 0

- name: Zdefiniuj nową sieć
  command: virsh net-define /tmp/{{ vm_network }}.xml
  when: net_check.rc != 0

- name: Włącz autostart sieci
  command: virsh net-autostart {{ vm_network }}
  when: net_check.rc != 0

- name: Uruchom sieć
  command: virsh net-start {{ vm_network }}
  when: net_check.rc != 0

- name: Tworzenie sieci NAT
  command: >
    virsh net-define /etc/libvirt/qemu/networks/{{ vm_network }}.xml
  args:
    creates: "/etc/libvirt/qemu/networks/{{ vm_network }}.xml"

- name: Uruchom sieć NAT
  command: virsh net-start {{ vm_network }}
  when: nat_port_forwarding is not defined

- name: Dodaj port forwarding do sieci NAT
  block:
    - name: Zatrzymaj sieć NAT
      command: virsh net-destroy {{ vm_network }}

    - name: Usuń istniejącą konfigurację NAT
      command: virsh net-undefine {{ vm_network }}

    - name: Renderuj konfigurację NAT z port forwarding
      template:
        src: nat-port-forwarding.xml.j2
        dest: "/etc/libvirt/qemu/networks/{{ vm_network }}.xml"

    - name: Uruchom sieć NAT z port forwarding
      command: virsh net-start {{ vm_network }}
  when: nat_port_forwarding is defined
