- name: Usuwanie VM
  hosts: localhost
  become: true
  vars_files:
    - ../vars/vm_config.yaml
  tasks:
    - name: Wyłącz VM
      command: virsh destroy {{ item.name }}
      ignore_errors: yes
      loop: "{{ vms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Usuń VM
      command: virsh undefine {{ item.name }} --remove-all-storage
      loop: "{{ vms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Usuń dynamiczne VM z inventory
      blockinfile:
        path: "{{ playbook_dir }}/../inventory/hosts"
        state: absent
        marker: "# {mark} DYNAMIC INVENTORY FOR VM {{ item.name }}"
      loop: "{{ vms }}"
      loop_control:
        label: "{{ item.name }}"