- name: Usuwanie wszystkich VM
  hosts: localhost
  become: true
  tasks:
    - name: Pobierz listę VM
      shell: virsh list --all --name
      register: vms
      changed_when: false

    - name: Zatrzymaj VM
      command: "virsh destroy {{ item }}"
      loop: "{{ vms.stdout_lines }}"
      ignore_errors: true

    - name: Undefine VM i usuń storage
      command: "virsh undefine {{ item }} --remove-all-storage"
      loop: "{{ vms.stdout_lines }}"
      ignore_errors: true

    - name: Usuń ISO z cloud-init
      file:
        path: "/var/lib/libvirt/images/{{ item }}-seed.iso"
        state: absent
      loop: "{{ vms.stdout_lines }}"
      ignore_errors: true
    
    - name: Usuń dysk VM
      file:
        path: "/var/lib/libvirt/images/{{ item }}.qcow2"
        state: absent
      loop: "{{ vms.stdout_lines }}"
      ignore_errors: true

    - name: Usuń tymczasowy user-data
      file:
        path: "/tmp/{{ item }}-user-data"
        state: absent
      loop: "{{ vms.stdout_lines }}"
      ignore_errors: true

    - name: Usuń tymczasowy meta-data
      file:
        path: "/tmp/{{ item }}-meta-data"
        state: absent
      loop: "{{ vms.stdout_lines }}"
      ignore_errors: true

    - name: Usuń sieci
      shell: |
        virsh net-destroy {{ item }} || true
        virsh net-undefine {{ item }} || true
      loop:
        - nat0
        - br0